include $(PRJROOT)/inc.mk

all: build

build:
	@./setup.sh

clean:
	@$(RM) -rf cJSON
	@$(RM) -rf mosquitto-2.0.14
	@$(RM) -rf libwebsockets
	@$(RM) -rf mongo-c-driver-1.20.1
	@$(RM) -rf curl-7.82.0
	@$(RM) -rf SDL2-2.0.20
	@$(RM) -rf mpv-build
	@clear
